name: Build and Test

permissions:
  contents: write
  statuses: write
  actions: read
  pull-requests: write

on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'cicd*.groovy'
      - '**/LICENSE'
      - 'README.md'
  workflow_dispatch:

jobs:
  build-and-test:
    if: (github.event.issue.pull_request && contains(github.event.comment.body, '/run tests')) || github.event_name == 'workflow_dispatch' || github.event_name == 'pull_request_target'
    uses: zopencommunity/meta/.github/workflows/build_and_test.yml@main
    secrets: inherit

  check-for-bump-PR:
    needs: build-and-test
    if: success()  # ✅ Only run if build-and-test succeeded
    runs-on: ubuntu-latest
    steps:
      - name: Add "automerge" label if latest committer email is bump-action@github
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            if (!pr) {
              console.log("Not a PR event. Skipping.");
              return;
            }

            const { owner, repo } = context.repo;
            const prNumber = pr.number;

            const { data: commits } = await github.rest.pulls.listCommits({
              owner,
              repo,
              pull_number: prNumber
            });

            if (!commits.length) {
              console.log("No commits found. Skipping.");
              return;
            }

            const latestEmail = commits[commits.length - 1].commit.committer.email;
            console.log(`Latest committer email: ${latestEmail}`);

            if (latestEmail === "bump-action@github") {
              console.log("Email matches bump-action@github. Adding label.");
              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: prNumber,
                labels: ["automerge"]
              });
            } else {
              console.log("Email does not match bump-action@github. Skipping label.");
            }
